description: >
  This is a sample executor using Nix on a Docker executor.
docker:
  - image: 'nixos/nix:<<parameters.tag>>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific nixos/nix image variant:
      https://hub.docker.com/r/nixos/nix/tags
    type: string
